### PR TITLE
add logic for dynamic rights reserved year

### PR DESCRIPTION
**Pull request by marsinearth**
because changing the year every time is too annoying

### CODE REVIEW

**Comment by marsinearth** [comment]
@hyochan have you checked this?

**Comment by hyochan** [comment]
@marsinearth I did but I was curious if we had to update the year everytime. [Accordingly](https://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated), I don't feel like we should update this and previously it was `2017` and I think someone has changed this (maybe you).

**Comment by marsinearth** [comment]
yes I did it. You should update that to the current year otherwise it's not indicating that all rights reserved to you in current time. An outdated year on "All right reserved on dooboolab in year XXXX"  has a nuance that the website is not being managed properly and being abandoned.

**Comment by hyochan** [comment]
@marsinearth What about 2017~current?

**Review by hyochan — APPROVED** [review]
👍

**Pull request merged**
